Removed Large Top App Bar because of crash when rotating device
Sharing state between the two types of app bars was causing crashes
because of values outside the valid color range:

    java.lang.IllegalArgumentException: red = 0.09803922, green = 0.10980392, blue = 0.11764706, alpha = 1.375 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)