Disabled minification due to crash on old Android
Fixes #326

This is the stacktrace:

01-14 00:00:30.642 4090-4090/com.nononsenseapps.feeder E/dalvikvm:
Could not find class 'android.util.Size', referenced from method
android.support.v4.media.MediaDescriptionCompatApi21$Builder.bundleOf
01-14 00:00:30.642 4090-4090/com.nononsenseapps.feeder E/dalvikvm:
Could not find class 'android.util.SizeF', referenced from method
android.support.v4.media.MediaDescriptionCompatApi21$Builder.bundleOf
01-14 00:00:30.642 4090-4090/com.nononsenseapps.feeder E/dalvikvm:
Could not find class 'android.text.PrecomputedText', referenced from
method
android.support.v4.media.MediaDescriptionCompatApi21$Builder.setPrecomputedText
01-14 00:00:30.652 4090-4090/com.nononsenseapps.feeder E/dalvikvm:
Could not find class
'androidx.work.impl.background.systemjob.SystemJobService', referenced
from method
androidx.work.impl.Schedulers.createBestAvailableBackgroundScheduler
01-14 00:00:30.652 4090-4090/com.nononsenseapps.feeder E/dalvikvm:
Could not find class
'androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateCallback',
referenced from method
androidx.work.impl.constraints.trackers.NetworkStateTracker.<init>
01-14 00:00:30.662 4090-4090/com.nononsenseapps.feeder
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.VerifyError: kotlinx/coroutines/AbstractCoroutine
        at
        android.support.v4.media.MediaDescriptionCompatApi21$Builder.launch$default(MediaDescriptionCompatApi21.java:6)
        at
        androidx.lifecycle.LifecycleCoroutineScopeImpl.register(Lifecycle.kt:1)
        at
        androidx.lifecycle.LifecycleKt.getCoroutineScope(Lifecycle.kt:7)
        at
        androidx.lifecycle.LifecycleOwnerKt.getLifecycleScope(LifecycleOwner.kt:1)
        at
        com.nononsenseapps.feeder.ui.FeedActivity.<init>(FeedActivity.kt:11)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1130)
        at
        android.app.Instrumentation.newActivity(Instrumentation.java:1061)
        at
        android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2128)
        at
        android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
        at
        android.app.ActivityThread.access$600(ActivityThread.java:141)
        at
        android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at
        com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at
        com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)